apiVersion: v1
kind: Service
metadata:
  name: backend-api01
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: api01
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 4443
      name: https
      targetPort: 4443