apiVersion: v1
kind: Service
metadata:
  name: krakend-service-nodeport
  namespace: gw-krakend
spec:
  type: NodePort
  selector:
    app: krakend
  ports:
    - port: 8000
      name: http
      targetPort: 8000
      nodePort: 31005