apiVersion: v1
kind: Service
metadata:
  name: konga
  namespace: gw-kong
spec:
  type: ClusterIP
  selector:
    app: konga
  ports:
    - port: 1337
      name: http
      targetPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: konga-nodeport
  namespace: gw-kong
spec:
  type: NodePort
  selector:
    app: konga
  ports:
    - port: 1337
      targetPort: 1337
      nodePort: 30002