apiVersion: v1
kind: Service
metadata:
  name: kong-api
  namespace: gw-kong
spec:
  type: ClusterIP
  selector:
    app: kong-api
  ports:
    - port: 8000
      name: http
      targetPort: 8000
    - port: 8443
      name: https
      targetPort: 8443
    - port: 8001
      name: admin
      targetPort: 8001
    - port: 8444
      name: admin-ssl
      targetPort: 8444
---
apiVersion: v1
kind: Service
metadata:
  name: kong-api-nodeport
  namespace: gw-kong
spec:
  type: NodePort
  selector:
    app: kong-api
  ports:
    - port: 8000
      name: http
      targetPort: 8000
      nodePort: 31001
    - port: 8443
      name: https
      targetPort: 8443
      nodePort: 31002
    - port: 8001
      name: admin
      targetPort: 8001
      nodePort: 31003
    - port: 8444
      name: admin-ssl
      targetPort: 8444
      nodePort: 31004