apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database-deployment
  namespace: gw-kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-database
  template:
    metadata:
      name: kong-database
      labels:
        app: kong-database
    spec:
      containers:
        - name: kong-database
          image: postgres:9.6
          volumeMounts:
            - name: kong-database-storage
              mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_USER
            value: "kong"
          - name: POSTGRES_DB
            value: "kong"
          - name: POSTGRES_PASSWORD
            value: "kong"
          ports:
          - containerPort: 5432
      volumes:
        - name: kong-database-storage
          persistentVolumeClaim:
            claimName: kong-pvc