apiVersion: v1
kind: Pod
metadata:
  name: kong-migrations-pod
  namespace: gw-kong
spec:
  restartPolicy: Never
  containers:
    - name: kong-migrations
      image: kong
      command: ["kong"]
      args: ["migrations", "bootstrap"]
      env:
      - name: KONG_DATABASE
        value: "postgres"
      - name: KONG_PG_HOST
        value: "kong-database"
      - name: KONG_PG_PASSWORD
        value: "kong"
      - name: KONG_CASSANDRA_CONTACT_POINTS
        value: "kong-database"