apiVersion: v1
kind: PersistentVolume
metadata:
  name: kong-pv-volume
  namespace: gw-kong
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"