apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-pvc
  namespace: gw-kong
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi